version: "3.5"
services:
  php:
    build:
      dockerfile: .docker/xdebug/Dockerfile
      context: .
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 9000:9000
  composer:
    image: composer:latest
    working_dir: /app
    volumes:
      - ./:/app
      - ./.composer:/composer